import { v4 as uuid } from "uuid";

export const videos = [
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=2Oy4HpUJSgE",
    categoryName: "Comedy",
    cardImg: "https://i.ytimg.com/vi/2Oy4HpUJSgE/hq720.jpg",
    cardTitle: "Ready",
    creator: "Rahul Subramanian",
    description: "RAHUL SUBRAMANIAN | LIVE IN BANGALORE | CROWD WORK (PART 1)",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=T18vEKmT4lg",
    categoryName: "Comedy",
    cardImg: "https://i.ytimg.com/vi/T18vEKmT4lg/hq720.jpg",
    cardTitle: "Ready",
    creator: "Rahul Subramanian",
    description: "RAHUL SUBRAMANIAN | CROWD WORK | THE COIN DROP MYSTERY",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=t4BfHoHawAM",
    categoryName: "Comedy",
    cardImg: "https://i.ytimg.com/vi/t4BfHoHawAM/hq720.jpg",
    cardTitle: "Ready",
    creator: "Munawar Faruqui",
    description: "Stand-Up Comedy | Crowd Work by Munawar Faruqui",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=J38ZBIvLank",
    categoryName: "Comedy",
    cardImg: "	https://i.ytimg.com/vi/J38ZBIvLank/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Gaurav Kapoor",
    description: "Bachpan ka pyaar by Gaurav kapoor | Stand up Comedy",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=sU0f5GLJMHE",
    categoryName: "Podcast",
    cardImg: "https://i.ytimg.com/vi/sU0f5GLJMHE/hq720.jpg",
    cardTitle: "Ready",
    creator: "Raj Shamani",
    description: "Kunal Shah On Startups, Indian Billionaires & Credit Cards",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=B9jZABnvq9A",
    categoryName: "Podcast",
    cardImg: "https://i.ytimg.com/vi/B9jZABnvq9A/hq720.jpg",
    cardTitle: "Ready",
    creator: "Raj Shamani",
    description:
      "OYO's Founder - Ritesh Agarwal On Building A Billion Dollar Hotel Startup",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=9yCqE-uE6HE",
    categoryName: "Podcast",
    cardImg: "https://i.ytimg.com/vi/9yCqE-uE6HE/hq720.jpg",
    cardTitle: "Ready",
    creator: "Raj Shamani",
    description:
      "TOP 10 Rules For Success In Finance, Career & Relationships | Ft. Anant & Rishabh",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=n_Wno11awXA&t=1409s",
    categoryName: "Podcast",
    cardImg: "	https://i.ytimg.com/vi/n_Wno11awXA/hq720.jpg",
    cardTitle: "Ready",
    creator: "Raj Shamani",
    description:
      "How to be a Successful Creator? Future of Content Creation | ft. Manish Pandey ",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=GbfjAeHX4P0",
    categoryName: "Song",
    cardImg: "https://i.ytimg.com/vi/GbfjAeHX4P0/hq720.jpg",
    cardTitle: "Ready",
    creator: "Jassie Gill",
    description:
      "Pyaar Mangdi | Jassi Gill Ft Happy Raikoti | New Romantic Song 2021 | Avvy Sra | Yashika",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=L7mfjvdnPno",
    categoryName: "Song",
    cardImg: "https://i.ytimg.com/vi/L7mfjvdnPno/hq720.jpg",
    cardTitle: "Ready",
    creator: "Trevor Daniel",
    description: "Trevor Daniel - Falling (Official Music Video)",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=q-U5nCDAgtY",
    categoryName: "Song",
    cardImg: "	https://i.ytimg.com/vi/q-U5nCDAgtY/hq720.jpg",
    cardTitle: "Ready",
    creator: "Diljit Dosanjh",
    description:
      "DILJIT DOSANJH: Black & White (Official Music Video) MoonChild Era | Intense | Raj Ranjodh",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=cl0a3i2wFcc",
    categoryName: "Song",
    cardImg: "https://i.ytimg.com/vi/cl0a3i2wFcc/hq720.jpg",
    cardTitle: "Ready",
    creator: "Diljit Dosanjh",
    description: "Diljit Dosanjh - G.O.A.T. (Official Music Video)",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=S_V4CdP6aLA&t=180s",
    categoryName: "Self help",
    cardImg: "https://i.ytimg.com/vi/S_V4CdP6aLA/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Matt D'Avella",
    description: "I read 100 self-help books. Here’s what I learned…",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=6x1i0K4Eg1g",
    categoryName: "Self help",
    cardImg: "https://i.ytimg.com/vi/6x1i0K4Eg1g/hq720.jpg",
    cardTitle: "Ready",
    creator: "Ali Abdaal",
    description: "12 Podcasts that Changed My Life",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=wIIGCTIpRMk&t=185s",
    categoryName: "Self help",
    cardImg: "https://i.ytimg.com/vi/wIIGCTIpRMk/hq720.jpg",
    cardTitle: "Ready",
    creator: "Matt D'Avella",
    description: "10 small changes that will improve your life.",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=aje9UGNi_l0",
    categoryName: "Self help",
    cardImg: "https://i.ytimg.com/vi/aje9UGNi_l0/hq720.jpg",
    cardTitle: "Ready",
    creator: "Pick Up Limes",
    description: "Why you’re always tired (+ food fixes!)",
  },
];
