import { v4 as uuid } from "uuid";

export const videos = [
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Comedy",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Comedy",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Comedy",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Comedy",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=sU0f5GLJMHE",
    categoryName: "Podcast",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Raj Shamani",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=B9jZABnvq9A",
    categoryName: "Podcast",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Raj Shamani",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=nnEZVVC4Ap8&t=3542s",
    categoryName: "Podcast",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Raj Shamani",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=n_Wno11awXA&t=1409s",
    categoryName: "Podcast",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Raj Shamani",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=3AuzANuYggk",
    categoryName: "Song",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Song",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Song",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Song",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Self help",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Self help",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Self help",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
  {
    _id: uuid(),
    videoLink: "https://www.youtube.com/watch?v=tPXYWRGNl7s",
    categoryName: "Self help",
    cardImg: "https://img.youtube.com/vi/tPXYWRGNl7s/hqdefault.jpg",
    cardTitle: "Ready",
    creator: "Samyak Shah",
    description: "",
  },
];
