import { v4 as uuid } from "uuid";

export const videos = [
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=2Oy4HpUJSgE",
    category: "Comedy",
    cover: "https://i.ytimg.com/vi/2Oy4HpUJSgE/hq720.jpg",
    title: "Ready",
    date: "1 year ago",
    views: "10M views",
    creator: "Rahul Subramanian",
    description: "RAHUL SUBRAMANIAN | LIVE IN BANGALORE | CROWD WORK (PART 1)",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=T18vEKmT4lg",
    category: "Comedy",
    cover: "https://i.ytimg.com/vi/T18vEKmT4lg/hq720.jpg",
    title: "Ready",
    date: "2 years ago",
    views: "8M views",
    creator: "Rahul Subramanian",
    description: "RAHUL | CROWD WORK | THE COIN DROP MYSTERY",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=t4BfHoHawAM",
    category: "Comedy",
    cover: "https://i.ytimg.com/vi/t4BfHoHawAM/hq720.jpg",
    title: "Ready",
    date: "8 months ago",
    views: "11M views",
    creator: "Munawar Faruqui",
    description: "Stand-Up Comedy | Crowd Work by Munawar Faruqui",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=J38ZBIvLank",
    category: "Comedy",
    cover: "	https://i.ytimg.com/vi/J38ZBIvLank/hqdefault.jpg",
    title: "Ready",
    date: "2 months ago",
    views: "2M views",
    creator: "Gaurav Kapoor",
    description: "Bachpan ka pyaar by Gaurav kapoor | Stand up Comedy",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=sU0f5GLJMHE",
    category: "Podcast",
    cover: "https://i.ytimg.com/vi/sU0f5GLJMHE/hq720.jpg",
    title: "Ready",
    date: "15 days ago",
    views: "256K views",
    creator: "Raj Shamani",
    description: "Kunal Shah On Startups, Indian Billionaires & Credit Cards",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=B9jZABnvq9A",
    category: "Podcast",
    cover: "https://i.ytimg.com/vi/B9jZABnvq9A/hq720.jpg",
    title: "Ready",
    date: "4 hours ago",
    views: "500K views",
    creator: "Raj Shamani",
    description:
      "OYO's Founder - Ritesh Agarwal On Building A Billion Dollar Hotel Startup",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=9yCqE-uE6HE",
    category: "Podcast",
    cover: "https://i.ytimg.com/vi/9yCqE-uE6HE/hq720.jpg",
    title: "Ready",
    date: "5 days ago",
    views: "100K views",
    creator: "Raj Shamani",
    description:
      "TOP 10 Rules For Success In Finance, Career & Relationships | Ft. Anant & Rishabh",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=n_Wno11awXA&t=1409s",
    category: "Podcast",
    cover: "	https://i.ytimg.com/vi/n_Wno11awXA/hq720.jpg",
    title: "Ready",
    date: "10 days ago",
    views: "100Kviews",
    creator: "Raj Shamani",
    description:
      "How to be a Successful Creator? Future of Content Creation | ft. Manish Pandey ",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=GbfjAeHX4P0",
    category: "Song",
    cover: "https://i.ytimg.com/vi/GbfjAeHX4P0/hq720.jpg",
    title: "Ready",
    date: "1.5 years ago",
    views: "100M views",
    creator: "Jassie Gill",
    description:
      "Pyaar Mangdi | Jassi Gill Ft Happy Raikoti | New Romantic Song 2021 | Avvy Sra | Yashika",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=L7mfjvdnPno",
    category: "Song",
    cover: "https://i.ytimg.com/vi/L7mfjvdnPno/hq720.jpg",
    title: "Ready",
    date: "3 years ago",
    views: "40M views",
    creator: "Trevor Daniel",
    description: "Trevor Daniel - Falling (Official Music Video)",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=q-U5nCDAgtY",
    category: "Song",
    cover: "	https://i.ytimg.com/vi/q-U5nCDAgtY/hq720.jpg",
    title: "Ready",
    date: "1 year ago",
    views: "30M views",
    creator: "Diljit Dosanjh",
    description:
      "DILJIT DOSANJH: Black & White (Official Music Video) MoonChild Era | Intense | Raj Ranjodh",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=cl0a3i2wFcc",
    category: "Song",
    cover: "https://i.ytimg.com/vi/cl0a3i2wFcc/hq720.jpg",
    title: "Ready",
    date: "1.5 years ago",
    views: "100M views",
    creator: "Diljit Dosanjh",
    description: "Diljit Dosanjh - G.O.A.T. (Official Music Video)",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=S_V4CdP6aLA&t=180s",
    category: "Self help",
    cover: "https://i.ytimg.com/vi/S_V4CdP6aLA/hqdefault.jpg",
    title: "Ready",
    date: "5 years ago",
    views: "1.1M views",
    creator: "Matt D'Avella",
    description: "I read 100 self-help books. Here’s what I learned…",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=6x1i0K4Eg1g",
    category: "Self help",
    cover: "https://i.ytimg.com/vi/6x1i0K4Eg1g/hq720.jpg",
    title: "Ready",
    date: "1 year ago",
    views: "101K views",
    creator: "Ali Abdaal",
    description: "12 Podcasts that Changed My Life",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=wIIGCTIpRMk&t=185s",
    category: "Self help",
    cover: "https://i.ytimg.com/vi/wIIGCTIpRMk/hq720.jpg",
    title: "Ready",
    date: "9 months ago",
    views: "786Kviews",
    creator: "Matt D'Avella",
    description: "10 small changes that will improve your life.",
  },
  {
    _id: uuid(),
    url: "https://www.youtube.com/watch?v=aje9UGNi_l0",
    category: "Self help",
    cover: "https://i.ytimg.com/vi/aje9UGNi_l0/hq720.jpg",
    title: "Ready",
    date: "3 years ago",
    views: "3M views",
    creator: "Pick Up Limes",
    description: "Why you’re always tired (+ food fixes!)",
  },
];
